Move bootstrap code out of setup

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -8,16 +8,21 @@ DOTFILES_DIR="$HOME/dotfiles"
 DOTFILES_REPO="git@github.com:fernandoacorreia/dotfiles.git"
 KEYFILE="$HOME/.ssh/id_ed25519"
 
-function macos_cli_dev_tools_installed() {
+missing_executable() {
+  local executable=$1
+  ! [ -x "$(command -v ${executable})" ]
+}
+
+macos_cli_dev_tools_installed() {
   xcode-select --print-path &>/dev/null
 }
 
-function macos_install_cli_dev_tools() {
+macos_install_cli_dev_tools() {
   if ! macos_cli_dev_tools_installed; then
     echo "Installing command-line developer tools"
     xcode-select --install
     while ! cli_dev_tools_installed; do
-      echo "Waiting for installation to finish"
+      echo "Waiting for installation to finish (look for a dialog window)"
       sleep 10
     done
     # Required for pyenv: https://github.com/pyenv/pyenv/issues/1219
@@ -25,7 +30,20 @@ function macos_install_cli_dev_tools() {
   fi
 }
 
-function macos_create_ssh_key() {
+macos_install_brew() {
+  if ! test -f /opt/homebrew/bin/brew; then
+    echo "Installing Homebrew"
+    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+  fi
+  eval "$(/opt/homebrew/bin/brew shellenv)"
+}
+
+macos_install_git() {
+  echo "Invoking git to trigger automated setup if it's not installed"
+  git --version
+}
+
+macos_create_ssh_key() {
   if ! test -f "$KEYFILE"; then
     echo "Creating ssh key"
     ssh-keygen -t ed25519 -f "$KEYFILE" -C "$(hostname)"
@@ -37,7 +55,7 @@ function macos_create_ssh_key() {
   fi
 }
 
-function macos_add_ssh_key_to_agent() {
+macos_add_ssh_key_to_agent() {
   echo "Adding ssh key to ssh agent"
   # Set config file
   if ! grep id_ed25519 ~/.ssh/config &>/dev/null; then
@@ -54,15 +72,15 @@ EOF
   ssh-add -K "$KEYFILE"
 }
 
-function ubuntu_install_git() {
-  if ! which git &>/dev/null; then
+ubuntu_install_git() {
+  if missing_executable git; then
     echo "Installing git"
     apt-get update
     apt-get install -y git
   fi
 }
 
-function ubuntu_create_ssh_key() {
+ubuntu_create_ssh_key() {
   if ! test -f "$KEYFILE"; then
     echo "Creating ssh key"
     ssh-keygen -t ed25519 -f "$KEYFILE" -C "$(hostname)"
@@ -74,7 +92,7 @@ function ubuntu_create_ssh_key() {
   fi
 }
 
-function ubuntu_add_ssh_key_to_agent() {
+ubuntu_add_ssh_key_to_agent() {
   echo "Adding ssh key to ssh agent"
   # Start agent
   eval "$(ssh-agent -s)"
@@ -82,7 +100,7 @@ function ubuntu_add_ssh_key_to_agent() {
   ssh-add "$KEYFILE"
 }
 
-function detect_platform() {
+detect_platform() {
   if [ "${OSTYPE//[0-9.]/}" == "darwin" ]; then
     export PLATFORM="macos"
   elif cat /etc/*release | grep ^NAME | grep Ubuntu &>/dev/null; then
@@ -92,10 +110,12 @@ function detect_platform() {
   fi
 }
 
-function first_time_setup() {
+first_time_setup() {
   detect_platform
   if [ "$PLATFORM" == "macos" ]; then
     macos_install_cli_dev_tools
+    macos_install_brew
+    macos_install_git
     macos_create_ssh_key
     macos_add_ssh_key_to_agent
   elif [ "$PLATFORM" == "ubuntu" ]; then
@@ -108,7 +128,7 @@ function first_time_setup() {
   fi
 }
 
-function clone_repository() {
+clone_repository() {
   if ! test -d $DOTFILES_DIR; then
     echo "Cloning from $DOTFILES_REPO"
     cd $HOME
@@ -116,10 +136,27 @@ function clone_repository() {
   fi
 }
 
-function run_setup() {
+upgrade_pip() {
+  if missing_executable pip3; then
+    echo "pip3 not found"
+    exit 1
+  fi
+  echo "Upgrading pip3"
+  sudo --set-home pip3 install --upgrade pip
+}
+
+install_ansible() {
+  if missing_executable ansible-playbook; then
+    upgrade_pip
+    echo "Installing Ansible"
+    sudo pip3 install ansible
+  fi
+}
+
+run_setup() {
   echo "Running setup"
   cd "$DOTFILES_DIR"
-  echo ./setup
+  ./setup
 }
 
 if ! test -d "$DOTFILES_DIR"; then
@@ -127,4 +164,5 @@ if ! test -d "$DOTFILES_DIR"; then
   clone_repository
 fi
 
+install_ansible
 run_setup
